env:
  global:
    - PATH: /usr/local/texlive/bin/x86_64-linux:$PATH
    - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
#before_script:
#  - cd ./developers/ && sudo -E ./texlive_install.sh && cd ../
script:
  - sudo -E make tex_env
  - make all
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./developers/deploy-ghpages.sh; fi
